use practice;

CREATE TABLE marketing_customers (
    ID INT PRIMARY KEY,
    Year_Birth INT,
    Education VARCHAR(50),
    Marital_Status VARCHAR(50),
    Income FLOAT,
    Kidhome INT,
    Teenhome INT,
    Dt_Customer DATE,
    Recency INT,
    MntWines INT,
    MntFruits INT,
    MntMeatProducts INT,
    MntFishProducts INT,
    MntSweetProducts INT,
    MntGoldProds INT,
    NumDealsPurchases INT,
    NumWebPurchases INT,
    NumCatalogPurchases INT,
    NumStorePurchases INT,
    NumWebVisitsMonth INT,
    AcceptedCmp3 INT,
    AcceptedCmp4 INT,
    AcceptedCmp5 INT,
    AcceptedCmp1 INT,
    AcceptedCmp2 INT,
    Response INT,
    Complain INT,
    Total_Spend FLOAT,
    Total_Purchases INT,
    Web_revenue FLOAT,
    Store_revenue FLOAT,
    Catalog_revenue FLOAT,
    Inc_group VARCHAR(30),
    Age INT,
    Age_group VARCHAR(30),
    Country VARCHAR(50)
);
